// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAItbrSk370bD9UOvrU24H-DmQ2kbZTnMM',
    appId: '1:650860257352:web:aa6496aaac302fa945787d',
    messagingSenderId: '650860257352',
    projectId: 'flutter-notifications-37fb8',
    authDomain: 'flutter-notifications-37fb8.firebaseapp.com',
    storageBucket: 'flutter-notifications-37fb8.appspot.com',
    measurementId: 'G-WEVN0CZ3WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKsL1wzbiMZ8LwbdO9QH3BTp9WiOzsHds',
    appId: '1:650860257352:android:e2bbe3146346e37f45787d',
    messagingSenderId: '650860257352',
    projectId: 'flutter-notifications-37fb8',
    storageBucket: 'flutter-notifications-37fb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFjtfutaAVSda1oos5uQ5jD_wehtijUlY',
    appId: '1:650860257352:ios:905e552244b78a4345787d',
    messagingSenderId: '650860257352',
    projectId: 'flutter-notifications-37fb8',
    storageBucket: 'flutter-notifications-37fb8.appspot.com',
    iosClientId: '650860257352-8gljdq7tgqnfef3bfvphm1a7lgmok1il.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFjtfutaAVSda1oos5uQ5jD_wehtijUlY',
    appId: '1:650860257352:ios:ddd7558b8887a27645787d',
    messagingSenderId: '650860257352',
    projectId: 'flutter-notifications-37fb8',
    storageBucket: 'flutter-notifications-37fb8.appspot.com',
    iosClientId: '650860257352-9s2c8ino0fhfh9tc8pna9d9l4ebf5v49.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbn.RunnerTests',
  );
}
